# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4327a84e0b22ac1ea7e415ccead952b0ad4a3e14ce55961ff709a8bdd5444fc6b5b6657ce0426dcde4bdd52de00d9ab7079226ef078953dc0909399be6a80fd

test:
  secret_key_base: dbedf08ab57c68d4cd467a24ec492897428bcba11efda8af5ca1e8118c4db6f28c59648a33884b79cc3e67cab0dc655d0b3800c276f95f092420861eccd825b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
